/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_embulk_output_oracle_oci_OCI */

#ifndef _Included_org_embulk_output_oracle_oci_OCI
#define _Included_org_embulk_output_oracle_oci_OCI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_embulk_output_oracle_oci_OCI
 * Method:    open
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lorg/embulk/output/oracle/oci/TableInfo;)V
 */
JNIEXPORT void JNICALL Java_org_embulk_output_oracle_oci_OCI_open
  (JNIEnv *, jobject, jstring, jstring, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
